# Linear Regression
linear regression is a statistical method that allows us to summarize and study relationships between two or more continuous (quantitative) variables. One variable, denoted y, is regarded as the response, dependent, or outcome variable. The other variable(s), denoted X, are regarded as the predictor(s), independent, or feature variables.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [ ]:
data = pd.read_csv("insurance.csv")
data.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [ ]:
updated_data = pd.read_csv("insurance_updated.csv")
updated_data

,age_group_18-34,age_group_35-54,age_group_55+,is_female,bmi,children,is_smoker,expenses,region_southeast,bmi_cetogory_obese
0,1,0,0,1,-0.524321,-0.909234,1,16884,0,0
1,1,0,0,0,0.457496,-0.079442,0,1725,1,1
2,1,0,0,0,0.457496,1.580143,0,4449,1,1
3,1,0,0,0,-1.342502,-0.909234,0,21984,0,0
4,1,0,0,0,-0.360685,-0.909234,0,3866,0,0
...,...,...,...,...,...,...,...,...,...,...
1332,0,1,0,0,0.130224,1.580143,0,10600,0,1
1333,1,0,0,1,0.130224,-0.909234,0,2205,0,1
1334,1,0,0,1,0.948405,-0.909234,0,1629,1,1
1335,1,0,0,1,-0.851594,-0.909234,0,2007,0,0
1336,0,0,1,1,-0.197049,-0.909234,1,29141,0,0

In [6]:

final_df = updated_data[['age_group_18-34','age_group_35-54','age_group_55+', 'is_female', 'bmi', 'children', 'is_smoker', 'expenses','region_southeast','bmi_cetogory_obese']]

In [7]:
final_df

,age_group_18-34,age_group_35-54,age_group_55+,is_female,bmi,children,is_smoker,expenses,region_southeast,bmi_cetogory_obese
0,1,0,0,1,-0.524321,-0.909234,1,16884,0,0
1,1,0,0,0,0.457496,-0.079442,0,1725,1,1
2,1,0,0,0,0.457496,1.580143,0,4449,1,1
3,1,0,0,0,-1.342502,-0.909234,0,21984,0,0
4,1,0,0,0,-0.360685,-0.909234,0,3866,0,0
...,...,...,...,...,...,...,...,...,...,...
1332,0,1,0,0,0.130224,1.580143,0,10600,0,1
1333,1,0,0,1,0.130224,-0.909234,0,2205,0,1
1334,1,0,0,1,0.948405,-0.909234,0,1629,1,1
1335,1,0,0,1,-0.851594,-0.909234,0,2007,0,0
1336,0,0,1,1,-0.197049,-0.909234,1,29141,0,0

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [13]:
# Define the features (X) input and target (y) output variable
X = final_df.drop('expenses', axis=1)
# Define the target variable (y)
y = final_df['expenses']

In [14]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
# Create a Linear Regression model and fit it to the training data
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [38]:
# Make predictions on the test set
y_pred = model.predict(X_test)
y_pred

array([ 5902.38032669,  5152.58220059, 12912.90232099, 31598.12644368,
        7891.03057841, 11874.73564024, 31152.63151726,  2109.57460417,
       11031.29628704,  8706.93808416, 10873.40819462, 29458.6115974 ,
       30026.87959212, 16480.25079927, 12375.99416194,  7971.05771173,
        6968.07885489, 33998.68379165,  3390.43600972,  3032.52632769,
        6013.25253268, 30293.97807652, 12463.57940634, 30293.97807652,
       29581.3846657 ,  7795.37245994, 35323.40793018, 38253.80502353,
       10844.22493595, 13457.8833541 ,  6124.63950168, 11138.85526781,
        2344.1964549 , 12114.79197461, 34548.04993218, 11242.16936273,
        6186.92089311,  3919.27129468, 28451.84966814,  7016.23138952,
        6920.52835525, 30325.38282801, 35569.93064321, 10951.78391672,
        7266.58209078,  2209.06071086,  7020.01446194,  7426.07667861,
        2944.9410833 , 11377.30510676,  7485.01327755, 11210.76461124,
       30086.93298905,  5921.83930007, 11986.12260924, 11178.33289337,
        7135.6912326 ,  2646.48276321, 29915.49262312, 11488.69207576,
       13835.85404451, 10931.81018034, 11679.59141507,  2217.13358494,
       13708.79117455,  7565.04041086, 11449.2144502 , 29458.6115974 ,
       25375.42042887, 16420.24231813,  5595.84913252,  6025.15339499,
        6737.74680581,  2049.56612304, 11577.88381557,  1512.65796399,
       16289.35145995,  7592.57225832,  6630.18782504, 11478.39770887,
        6761.03376742, 15069.16495042, 15692.43481978, 11675.76342685,
       34529.12557203, 12739.28537804,  2117.64747825,  2941.11309507,
        6928.60122933,  5822.35319337, 17191.7723279 , 27276.530352  ,
        5697.56323371,  6033.22626906,  2507.51903095, 33473.67649491,
       10800.91932216,  6916.74528283,  5921.83930007,  7573.11328494,
       15186.93141222, 17800.58983038, 29478.11548658, 12821.48908837,
       35772.73084482,  1719.70305146, 29919.32061135, 28119.96970521,
       16857.66437048,  7135.6912326 , 11269.74612599, 11470.32483479,
        7059.49208751,  8829.71115246,  6829.11512263,  6120.81151346,
        2944.9410833 ,  5921.83930007,  6717.72815363,  7254.68122848,
       38333.31739385,  6431.17069585, 11238.34137451, 12312.15769259,
        7227.10446522, 11687.66428915,  5598.07712702, 11569.81094149,
       29677.04278417, 38842.64878963, 34728.09778542, 10904.23341708,
        1807.28829586,  8798.35131678,  9028.68336585,  9068.16099141,
       34062.52026101, 29589.50245558, 25566.31976818,  6112.73863938,
        4078.76588251,  4078.76588251, 34448.56382549,  6936.71901921,
        6717.72815363, 10307.31677691,  7553.09463276,  7227.10446522,
       34189.58313096, 15195.0042863 , 11978.04973516,  8110.02144398,
       10752.81170333, 15982.82026579,  7362.24020925, 29072.05326992,
       36330.16985944, 13370.8552289 ,  9897.47148782, 10215.90354429,
       10307.31677691,  5695.33523922, 15186.93141222, 15385.90362561,
       38245.73214945, 33911.09854725, 12212.67158589, 25792.86874483,
        2010.08849747,  3827.85806207,  2853.52785068,  6610.16917286,
        2408.03292426, 10662.53511893, 11580.10530838, 25943.73333939,
        3044.42718999, 10096.44370121,  6339.80237903, 12224.57244819,
       16666.76503116,  6323.61171507,  8197.60668838, 11072.38040801,
       34837.878259  , 11378.91160218,  8837.78402654,  8340.35349306,
        1910.60239078, 31061.21828464,  7119.50056864, 29987.44688236,
       10406.8028836 ,  3032.52632769,  2308.54681756,  5623.38097998,
       34010.58465395,  3879.79366912, 13367.6067697 , 17355.09490396,
       29092.0270063 , 24858.01615901,  6379.83712379, 14984.13121061,
       27782.03375956,  7059.49208751, 11878.56362847, 11687.66428915,
        2507.51903095, 35768.9028566 , 30922.29946818,  8408.47976407,
        2933.04022099,  7863.49873095, 10861.50733232,  6510.68306616,
        6522.58392847, 10912.30629116,  6300.32475347,  6025.15339499,
        2507.51903095, 36166.84728338, 35621.86625026, 12651.70013365,
       10442.45252094, 38042.93194784, 33175.21817482,  5595.84913252,
       29290.99921969,  2754.04174398, 15481.56174408, 28992.5408996 ,
        7405.50090723, 10414.87575768, 10483.53664192,  6590.71019948,
       10574.94987453,  6311.71085277,  6423.09782177,  3032.52632769,
        8539.32570645,  6033.22626906,  3251.47227746,  6292.25187939,
        2117.64747825,  6729.67393174,  4317.21572147, 12722.00298167,
        2607.00513765, 12224.57244819,  6860.51987412, 11569.81094149,
       11478.39770887, 16658.69215709, 35681.31761221, 24778.50378869,
       10972.89430132,  8232.79451228,  8798.35131678, 11687.66428915,
       31697.61255038, 38241.90416123, 17927.65270034, 15680.53395748,
       15374.00276331,  7894.85856663, 39387.62982275,  6192.7657727 ])

In [39]:
y_test

899      8688
1063     5708
1255    11436
298     38746
237      4463
        ...
534     13831
542     13887
759      3925
1283    47403
1284     8534
Name: expenses, Length: 268, dtype: int64

In [60]:
from sklearn.metrics import r2_score

# Calculate the R-squared value to evaluate the model's performance
r2 = r2_score(y_test, y_pred) 

print("R-squared value:", r2)

R-squared value: 0.78698804561261

In [59]:
# Perform 5-fold cross-validation and calculate R² scores
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    model, X, y,
    cv=5,
    scoring="r2"
)

print("CV R²:", scores.mean())

CV R²: 0.7397886360832172

In [ ]:
# Calculate the adjusted R-squared value
n = X_test.shape[0]  # Number of observations in the test set
p = X_test.shape[1]  # Number of predictors (features)
adjusted_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)
adjusted_r2

0.779557396040957

In [ ]:
# Calculate R² for both training and testing sets
train_r2 = r2_score(
    y_train,
    model.predict(X_train)
)

test_r2 = r2_score(
    y_test,
    model.predict(X_test)
)

print("Train R²:", train_r2)
print("Test R²:", test_r2)

Train R²: 0.72748227640554
Test R²: 0.78698804561261